services:
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v5.6.0
    ports:
      - 8080:8080
    networks:
      - vpc-bridge
    depends_on:
      - tyk-redis
      - auth-service
      - api-service
    volumes:
      - ./tyk-gateway/tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk-gateway/apps:/opt/tyk-gateway/apps
      - ./tyk-gateway/middleware:/opt/tyk-gateway/middleware
      - ./tyk-gateway/certs:/opt/tyk-gateway/certs
      - ./tyk-gateway/policies:/opt/tyk-gateway/policies
    environment:
      TYK_GW_SECRET: ${TYK_GW_SECRET}
      TYK_GW_HTTPSERVEROPTIONS_FLUSHINTERVAL: 1
      TYK_GW_ANALYTICSCONFIG_ENABLEGEOIP: true
      API_SERVICE_JWT_SECRET_BASE64: ${API_SERVICE_JWT_SECRET_BASE64}
      API_SERVICE_URL: http://api-service:8000
      AUTH_SERVICE_URL: http://auth-service:8000

  tyk-redis:
    image: redis:6.2.7-alpine
    volumes:
      - tyk-redis-data:/data
    networks:
      - vpc-bridge

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v1.11.0
    # ports:
    #   - 9093:8083
    #   - 9091:9091
    networks:
      - vpc-bridge
    volumes:
      - ./tyk-pump/pump.conf:/opt/tyk-pump/pump.conf
    environment:
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:-0}
      - TYK_LOGLEVEL=${PUMP_LOGLEVEL:-info}
    depends_on:
      - tyk-redis

  auth-postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - auth-postgres-vol-data:/var/lib/postgresql/data
      - ./auth-service/db/auth.sql:/docker-entrypoint-initdb.d/auth.sql
    environment:
      POSTGRES_USER: ${AUTH_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_SERVICE_POSTGRES_DB}
    networks:
      - vpc-bridge

  auth-service:
    image: supabase/gotrue:v2.158.1
    networks:
      - vpc-bridge
    depends_on:
      - auth-postgres
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8000/health',
        ]
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 8000
      API_EXTERNAL_URL: ${AUTH_SERVICE_API_EXTERNAL_URL}

      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${AUTH_SERVICE_POSTGRES_PASSWORD}@auth-postgres:5432/${AUTH_SERVICE_POSTGRES_DB}

      GOTRUE_SITE_URL: ${AUTH_SERVICE_SITE_URL}
      GOTRUE_URI_ALLOW_LIST: ${AUTH_SERVICE_ADDITIONAL_REDIRECT_URLS}
      GOTRUE_DISABLE_SIGNUP: ${AUTH_SERVICE_DISABLE_SIGNUP}

      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${AUTH_SERVICE_JWT_EXPIRY}
      GOTRUE_JWT_SECRET: ${AUTH_SERVICE_JWT_SECRET}

      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${AUTH_SERVICE_ENABLE_EMAIL_SIGNUP}
      GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED: ${AUTH_SERVICE_ENABLE_ANONYMOUS_USERS}
      GOTRUE_MAILER_AUTOCONFIRM: ${AUTH_SERVICE_ENABLE_EMAIL_AUTOCONFIRM}
      # GOTRUE_MAILER_SECURE_EMAIL_CHANGE_ENABLED: true
      # GOTRUE_SMTP_MAX_FREQUENCY: 1s
      GOTRUE_SMTP_ADMIN_EMAIL: ${AUTH_SERVICE_SMTP_ADMIN_EMAIL}
      GOTRUE_SMTP_HOST: ${AUTH_SERVICE_SMTP_HOST}
      GOTRUE_SMTP_PORT: ${AUTH_SERVICE_SMTP_PORT}
      GOTRUE_SMTP_USER: ${AUTH_SERVICE_SMTP_USER}
      GOTRUE_SMTP_PASS: ${AUTH_SERVICE_SMTP_PASS}
      GOTRUE_SMTP_SENDER_NAME: ${AUTH_SERVICE_SMTP_SENDER_NAME}
      GOTRUE_MAILER_URLPATHS_INVITE: ${AUTH_SERVICE_MAILER_URLPATHS_INVITE}
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: ${AUTH_SERVICE_MAILER_URLPATHS_CONFIRMATION}
      GOTRUE_MAILER_URLPATHS_RECOVERY: ${AUTH_SERVICE_MAILER_URLPATHS_RECOVERY}
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: ${AUTH_SERVICE_MAILER_URLPATHS_EMAIL_CHANGE}

      GOTRUE_EXTERNAL_PHONE_ENABLED: ${AUTH_SERVICE_ENABLE_PHONE_SIGNUP}
      GOTRUE_SMS_AUTOCONFIRM: ${AUTH_SERVICE_ENABLE_PHONE_AUTOCONFIRM}

      # Uncomment to enable custom access token hook. You'll need to create a public.custom_access_token_hook function and grant necessary permissions.
      # See: https://supabase.com/docs/guides/auth/auth-hooks#hook-custom-access-token for details
      # GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_ENABLED="true"
      # GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_URI="pg-functions://postgres/public/custom_access_token_hook"

      # GOTRUE_HOOK_MFA_VERIFICATION_ATTEMPT_ENABLED="true"
      # GOTRUE_HOOK_MFA_VERIFICATION_ATTEMPT_URI="pg-functions://postgres/public/mfa_verification_attempt"

      # GOTRUE_HOOK_PASSWORD_VERIFICATION_ATTEMPT_ENABLED="true"
      # GOTRUE_HOOK_PASSWORD_VERIFICATION_ATTEMPT_URI="pg-functions://postgres/public/password_verification_attempt"

  api-postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - api-pg-data:/var/lib/postgresql/data
    networks:
      - vpc-bridge
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: ${API_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${API_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${API_SERVICE_POSTGRES_DB}

  api-redis:
    image: redis/redis-stack
    restart: unless-stopped
    networks:
      - vpc-bridge
    # environment:
    #   REDIS_ARGS: --requirepass ${REDIS_PASSWORD}
    volumes:
      - api-redis-data:/data

  api-mqtt01:
    image: emqx:latest
    restart: unless-stopped
    volumes:
      - api-vol-emqx01-data:/opt/emqx/data
      - api-vol-emqx01-log:/opt/emqx/log
    environment:
      - 'EMQX_NODE__NAME=emqx@node01.emqx.io'
      - 'EMQX_CLUSTER__DISCOVERY_STRATEGY=static'
      - 'EMQX_CLUSTER__STATIC__SEEDS=[emqx@node01.emqx.io, emqx@node02.emqx.io]'
    networks:
      vpc-bridge:
        aliases:
          - node01.emqx.io

  api-mqtt02:
    image: emqx:latest
    restart: unless-stopped
    volumes:
      - api-vol-emqx02-data:/opt/emqx/data
      - api-vol-emqx02-log:/opt/emqx/log
    environment:
      - 'EMQX_NODE__NAME=emqx@node02.emqx.io'
      - 'EMQX_CLUSTER__DISCOVERY_STRATEGY=static'
      - 'EMQX_CLUSTER__STATIC__SEEDS=[emqx@node01.emqx.io, emqx@node02.emqx.io]'
    networks:
      vpc-bridge:
        aliases:
          - node02.emqx.io

  api-service:
    build: ./api-service
    networks:
      - vpc-bridge
    depends_on:
      - api-postgres
      - api-redis
      - api-mqtt01
      - api-mqtt02
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8000/health',
        ]
      timeout: 5s
      interval: 5s
      retries: 3
    environment:
      NODE_ENV: production
      # Common module
      APP_NAME: ${API_SERVICE_APP_NAME}
      APP_URL: ${API_SERVICE_APP_URL}
      APP_PORT: 8000
      LOG_LEVEL: info
      ## DB
      DATABASE_URL: postgresql://${API_SERVICE_POSTGRES_USER}:${API_SERVICE_POSTGRES_PASSWORD}@api-postgres:5432/${API_SERVICE_POSTGRES_DB}?schema=public
      REDIS_URL: redis://api-redis:6379/0
      ## Security
      VERIFY_TOKEN: FALSE
      # File module
      ## Storage
      USER_ASSET_BUCKET: isling-dev01-user-asset
      ## Credentials
      GOOGLE_APPLICATION_CREDENTIALS: ${API_SERVICE_GOOGLE_APPLICATION_CREDENTIALS}
      # Notification module
      NOTIFICATION_MQTT_URL: mqtt://api-mqtt01:2883
      ## unit: second
      NOTIFICATION_MERGE_THRESHOLD: 28800
      ## Distributed locks
      MUTEX_REDIS1_HOST: api-redis
      MUTEX_REDIS1_PORT: 6379
      MUTEX_REDIS2_HOST: api-redis
      MUTEX_REDIS2_PORT: 6379
      MUTEX_REDIS3_HOST: api-redis
      MUTEX_REDIS3_PORT: 6379

  monitor-grafana:
    image: grafana/grafana-oss:latest
    ports:
      - '1300:3000'
    restart: unless-stopped
    networks:
      - vpc-bridge
    volumes:
      - monitor-grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/

  monitor-prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - '9090:9090'
    networks:
      - vpc-bridge
    volumes:
      - monitor-prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/slos.rules.yml:/etc/prometheus/slos.rules.yml

  monitor-exporter:
    image: prom/node-exporter:latest
    networks:
      - vpc-bridge
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

volumes:
  tyk-redis-data:
  auth-postgres-vol-data:
  api-pg-data:
  api-redis-data:
  api-vol-emqx01-data:
  api-vol-emqx01-log:
  api-vol-emqx02-data:
  api-vol-emqx02-log:
  monitor-grafana:
  monitor-prometheus:

networks:
  vpc-bridge:
    driver: bridge
